version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "cargo"
    directory: "/stremio-core-kotlin"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "gradle"
    directory: "/stremio-core-kotlin/stremio-core-kotlin"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "cargo"
    directory: "/stremio-core"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "gradle"
    directory: "/vlc-android-sdk"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
